<%@ Page Title="Process Orders" Language="C#" MasterPageFile="~/MasterPages/FrontEnd.Master" AutoEventWireup="true" CodeBehind="ProcessOrders.aspx.cs" Inherits="Goblin.Secure.Staff.ProcessOrders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cphMain" runat="server">
    <h1><%:Page.Title %></h1>
    <fieldset>
        <legend>
            <b>Process Orders</b>
        </legend>

        <fieldset><legend>Order</legend>


            <asp:GridView ID="ProductGridView" runat="server"
                AutoGenerateSelectButton="False"
                AutoGenerateDeleteButton="True"
                
                OnRowDeleting ="ProductGridView_RowDeleting"
                DataKeyNames="LineItemId"
                GridLines="Vertical"
                CellPadding="4"
                ItemType="Goblin.Model.LineItem"
                SelectMethod="GetLineItems">

                <%--   375610038782002--%>


                <Columns>
                    <asp:TemplateField HeaderText="Add">
                        <ItemTemplate>
                            <asp:CheckBox ID="cboxProcessed" runat="server" AutoPostBack="true" OnCheckedChanged="cboxProcessed_CheckedChanged1"></asp:CheckBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

<%--                <Columns>
                    <asp:TemplateField HeaderText="Process">
                        <ItemTemplate>
                            <asp:CheckBox ID="cboxProcessed1" runat="server" AutoPostBack="true" OnCheckedChanged="cboxProcessed_CheckedChanged1"></asp:CheckBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>--%>

            </asp:GridView>

            <br />

            <asp:GridView ID="OrderGridView" runat="server"
                AutoGenerateSelectButton="False"
                AutoGenerateDeleteButton="True"
                OnRowDeleting="OrderGridView_RowDeleting"
                DataKeyNames="OrderId"
                GridLines="Vertical"
                CellPadding="4"
                ItemType="Goblin.Model.Order"
                SelectMethod="GetOrders">

                <%--   375610038782002--%>


<%--                <Columns>
                    <asp:TemplateField HeaderText="Process">
                        <ItemTemplate>
                            <asp:CheckBox ID="cboxProcessed" runat="server" AutoPostBack="true" OnCheckedChanged="cboxProcessed_CheckedChanged"></asp:CheckBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>--%>

                <Columns>
                    <asp:TemplateField HeaderText="Process">
                        <ItemTemplate>
                            <asp:CheckBox ID="cboxProcessed1" runat="server" AutoPostBack="true" OnCheckedChanged="cboxProcessed_CheckedChanged"></asp:CheckBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

            </asp:GridView>
        </fieldset>
    </fieldset>
</asp:Content>
