<%@ Page Title="Process Orders" Language="C#" MasterPageFile="~/MasterPages/AdminPanel.Master" AutoEventWireup="true" CodeBehind="ProcessOrders.aspx.cs" Inherits="GoblinV1.Secure.Staff.ProcessOrders" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cphMain" runat="server">
    <h1><%#:Title %></h1>
    <fieldset>
        <legend>
            <b>Process Orders</b>
        </legend>

        <asp:GridView ID="OrderGridView" runat="server"
            AutoGenerateSelectButton="False"
            AutoGenerateDeleteButton="True"
            OnRowDeleting="OrderGridView_RowDeleting"
            DataKeyNames="OrderId"
            GridLines="Vertical"
            CellPadding="4"
            ItemType="GoblinV1.Models.Order"
            SelectMethod="GetOrders">

            <Columns>
                <asp:TemplateField HeaderText="Process">
                    <ItemTemplate>
                        <asp:CheckBox ID="cboxProcessed" runat="server" AutoPostBack="true" OnCheckedChanged="cboxProcessed_CheckedChanged"></asp:CheckBox>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>

        </asp:GridView>
    </fieldset>
</asp:Content>
